# Generated by Django 6.0.1 on 2026-03-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productset_ready_time_alter_productset_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productset',
            options={'ordering': ['-id'], 'verbose_name': 'Топтом', 'verbose_name_plural': 'Топтомдор'},
        ),
        migrations.AddField(
            model_name='productset',
            name='description',
            field=models.TextField(blank=True, help_text='Топтомдун курамы же өзгөчөлүгү жөнүндө', null=True, verbose_name='Кошумча маалымат'),
        ),
        migrations.AlterField(
            model_name='productset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sets/', verbose_name='Сүрөтү'),
        ),
        migrations.AlterField(
            model_name='productset',
            name='pieces',
            field=models.PositiveIntegerField(help_text='Топтомдо канча даана бар?', verbose_name='Даана саны'),
        ),
        migrations.AlterField(
            model_name='productset',
            name='title',
            field=models.CharField(help_text='Мисалы: Кулпунай классик', max_length=200, verbose_name='Топтомдун аталышы'),
        ),
        migrations.AlterField(
            model_name='productset',
            name='whatsapp_msg',
            field=models.TextField(blank=True, help_text="Кардар 'Заказ берүү' баскычын басканда сизге келе турган текст", verbose_name='WhatsApp билдирүүсү'),
        ),
    ]
