# Generated by Django 6.0.1 on 2026-03-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productset_options_productset_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productset',
            name='video',
            field=models.FileField(blank=True, help_text='Эгер видео жүктөлсө, сайтта сүрөттүн ордуна видео ойноп турат.', null=True, upload_to='sets/videos/', verbose_name='Видео (MP4 формат сунушталат)'),
        ),
        migrations.AlterField(
            model_name='productset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sets/images/', verbose_name='Сүрөтү (Превью)'),
        ),
    ]
