# Generated by Django 6.0.3 on 2026-04-27 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productset_video_alter_productset_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Филиалдын аты')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug (URL үчүн)')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, verbose_name='Дареги')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активдүү')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалдар',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='productset',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_sets', to='shop.branch', verbose_name='Филиал'),
        ),
    ]
